strictPeerDependencies: false
nodeLinker: hoisted
minimumReleaseAge: 5760
shamefullyHoist: true
allowBuilds:
  '@parcel/watcher': false
  bootstrap-vue: false
  core-js: false
  core-js-pure: false
  maplibre-gl: false
  vue-material: false
